version: '3'
services:
  backend:
    build: ./
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      DB_URI: postgresql://postgres:postgres@database:5432/backend-db
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backend-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5


