"""Cambios 211020241827

Revision ID: 042c06e2be61
Revises: 1bbf66cfa710
Create Date: 2024-10-21 21:51:50.834221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042c06e2be61'
down_revision = '1bbf66cfa710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies_consumers',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('consumer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumers.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'consumer_id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    op.drop_table('companies_consumers')
    op.drop_table('companies')
    # ### end Alembic commands ###
