name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read
  statuses: write

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.2]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest --cov=src -v --cov-fail-under=65

